### ISSUE TITLE
wellcart/skeleton-application doesn't work correctly with internal php server

### ISSUE THREAD

**Issue by eugenzor** [wellcart/skeleton-application#1]
When I run this application with internal php server:
```bash
php -S localhost:8000 -t public public/index.php
```
I can't login into the Dashboard. With apache2 everything is ok. 
OS: ubuntu 15.10, PHP 5.6.11

**Comment by DmytroDenysenko** [comment]
That's related to special WellCart concept: execution flow have different contexts - common, frontend, backend, console.
I change url pattern matching for fix this.
