### ISSUE TITLE
Email confirmation doesn't work

### ISSUE THREAD

**Issue by eugenzor** [wellcart/skeleton-application#2]
I've set "Require Emails Confirmation" to "Yes" there: /admin/user/preferences/
but user can register without confirmation and confirmation message isn't sent.

**Comment by eugenzor** [comment]
May be that happened because of cache. After a couple of hours application starts sending mails, but I think that kind of options must be applied immediately.

**Comment by DmytroDenysenko** [comment]
Issue fixed in user module. Фll dependencies have been updated
