### ISSUE TITLE
Problem with Last Name in the registration form

### ISSUE THREAD

**Issue by eugenzor** [wellcart/skeleton-application#4]
In the registration form /user/register you have changed displey_name from zfcuser to first_name+last_name. Both of them are required. I think it's wrong. We can't require user last_name if he doesn't wont to tell it. Many application don't need last_name at all. In that case developers have to rewrite WellCart\User\EventListener\Registration\AddRequiredFieldsToFilter and WellCart\User\EventListener\Registration\AddRequiredFieldsToForm and replace text last_name field to hidden. It's like a crutch. I think it is better to allow developers to include or exclude last_name in the configuration files. Captcha is also desirable.

Thanks.

**Comment by DmytroDenysenko** [comment]
Thank you for attention.)
First & last name necessary for our product requirements (also, it's very common usage of user profiles). Captcha will be added soon as optional feature.
